#!/bin/bash
# Links the AI agent config into each installed agent tool.
#   ./ai_agents_init.sh              install
#   ./ai_agents_init.sh --uninstall  remove what this script installed
#
# Layout:
#   shared/   tool-neutral content (policy + Agent Skills) — reused by every tool
#   claude/   Claude Code adapter — loads shared/ using Claude's own syntax
#
# Only Claude Code is installed on this machine today, so it is the only adapter
# here. Adding another tool later = add its base dir to TOOL_DIRS (for skills)
# and write a small <tool>_adapter function below.

. "$(dirname "${BASH_SOURCE[0]}")/../lib/dotfiles.sh"
parse_mode "$@"

HERE="$DOTFILES_ROOT/ai-agents"
SHARED_DIR="$HERE/shared"
SKILLS_DIR="$SHARED_DIR/skills"
LOCAL_DIR="$HOME/.dotfiles_local/ai-agents"

# Agent tools that read personal skills from <base>/skills/, following the open
# Agent Skills standard (https://agentskills.io): one skill = one folder holding
# a SKILL.md. A tool is only touched if its base dir already exists — i.e. the
# tool is installed — so uninstalled tools are skipped instead of littering ~.
TOOL_DIRS=(
  "$HOME/.claude"   # Claude Code
)

# --- Claude Code adapter ----------------------------------------------------

claude_adapter() {
  local base="$HOME/.claude" config="$HERE/claude" hook

  echo "Claude Code ($(tilde "$base")):"
  if [ ! -d "$base" ]; then
    echo "  not installed — skipped"
    return
  fi

  if [ "$MODE" = uninstall ]; then
    # This repo owns everything it links under ~/.claude, so a scan is safe here
    # and picks up hooks added since. settings.json is a copy, not a link.
    unlink_all "$base" 2
    [ -f "$base/settings.json" ] && { rm "$base/settings.json"; echo "  removed:   $(tilde "$base")/settings.json"; }
    rmdir "$base/shared" 2>/dev/null
    return
  fi

  # Global memory entry point + the shared policy it @imports.
  link "$config/CLAUDE.md" "$base/CLAUDE.md"
  link "$SHARED_DIR/AGENTS.md" "$base/shared/AGENTS.md"

  # PreToolUse hooks — Claude Code is the only tool here that can hard-block.
  for hook in "$config"/hooks/*.sh; do
    [ -f "$hook" ] || continue
    chmod +x "$hook"
    link "$hook" "$base/hooks/$(basename "$hook")"
  done

  # Runtime-mutable file — copy, don't link.
  [ -f "$config/settings.json" ] && copy "$config/settings.json" "$base/settings.json"
}

# --- run --------------------------------------------------------------------

claude_adapter

# Portable Agent Skills — one folder linked into every installed tool.
echo ""
echo "Agent Skills (shared/skills/ -> <tool>/skills/):"
if [ -d "$SKILLS_DIR" ]; then
  shopt -s nullglob
  skills=("$SKILLS_DIR"/*/)
  shopt -u nullglob
  if [ ${#skills[@]} -eq 0 ]; then
    echo "  (no skills in shared/skills/ yet)"
  fi
  # <tool>/skills/ is a FLAT namespace shared by every source that links into it
  # — this repo, a team hub (e.g. elements/agents), personal folders. So never
  # take over a name we don't own: refresh our own links, warn and skip anything
  # else. Same rule the team's link-skills.sh follows, so the two can coexist.
  for skill in "${skills[@]}"; do
    src="${skill%/}"
    name="$(basename "$src")"
    for base in "${TOOL_DIRS[@]}"; do
      [ -d "$base" ] || continue
      dest="$base/skills/$name"
      if [ "$MODE" = uninstall ]; then
        unlink "$dest"
      elif is_ours "$dest"; then
        link "$src" "$dest"
      elif [ -L "$dest" ]; then
        echo "  SKIPPED:   $(tilde "$dest") already points elsewhere:" >&2
        echo "             $(readlink "$dest")" >&2
        echo "             Rename one of the colliding skills, or remove the link and re-run." >&2
      elif [ -e "$dest" ]; then
        echo "  SKIPPED:   $(tilde "$dest") exists and is not a symlink (personal skill?)." >&2
      else
        mkdir -p "$(dirname "$dest")"
        ln -s "$src" "$dest"
        echo "  linked:    $(tilde "$dest") -> $(tilde "$src")"
      fi
    done
  done
else
  echo "  (no shared/skills/ directory yet)"
fi

if [ "$MODE" = uninstall ]; then
  echo ""
  echo "Left alone: $(tilde "$LOCAL_DIR") (machine-local notes are not ours to delete)"
  echo ""
  echo "Done."
  exit 0
fi

# Machine-local additions: anything dropped into ~/.dotfiles_local/ai-agents/ is
# collected into an index the adapters import. Keeps work-machine-only or
# secret-ish context out of this repo.
echo ""
echo "Machine-local index ($(tilde "$LOCAL_DIR")/index.md):"
mkdir -p "$LOCAL_DIR"
INDEX="$LOCAL_DIR/index.md"

{
  echo "# Machine-local agent memory index"
  echo "# Auto-generated by ai_agents_init.sh — DO NOT EDIT BY HAND."
  echo "# Drop any *.md into $LOCAL_DIR/ and re-run ai_agents_init.sh."
  echo ""
  found=0
  for f in "$LOCAL_DIR"/*.md; do
    [ -f "$f" ] || continue
    [ "$(basename "$f")" = "index.md" ] && continue
    echo "@$f"
    found=$((found + 1))
  done
  if [ "$found" -eq 0 ]; then
    echo "# (no machine-local .md files yet)"
  fi
} > "$INDEX"

count=$(grep -c '^@' "$INDEX" || true)
echo "  regenerated with $count import(s)"

echo ""
echo "Done."
