" set autoread
" set encoding=utf-8
" set fileencoding=utf-8

" <---  COLOR  --->
colorscheme ron " set colorscheme

if !exists("g:syntax_on")
    syntax enable " enable syntax highlight
endif


" <---  TAB  --->
set tabstop=4 " change display tab size
set softtabstop=4 " change insert tab size
set shiftwidth=4 " change shift tab size
set expandtab " convert tab to space
" set shiftround " 
set smarttab "
set autoindent " inherit the indentation from above line
filetype indent on " enable indentation rules that are file-type specific


" <---  SEARCH  --->
set hlsearch " enable serch highlighting
nmap <leader><space> :nohlsearch<CR> " map key to clear highlight


" <---  UI  --->
set number " turn on line number
" set relativenumber " turn on relative number
function! TChangeNumbering() " change numbering between number and relativenumber
    set number! " toggle line number
    set relativenumber! " toggle relative number
endfunc
nmap <leader>n :call TChangeNumbering()<cr> " map key to call TChangeNumbering()

set listchars=tab:▸\ ,eol:¬ " set invisible characters
nmap <leader>l :set list!<CR> " map key to toggle list
" function! TList() " toggle display invisibles
"     set list! " set shortcut to toggle list
" endfunc
" nmap <leader>l :call TList()<cr> " map key to call TList()

nmap <leader>w :set wrap!<CR> " toggle wrapping code
set colorcolumn=80 " make red column
" set mouse=a " enable mouse
" set showcmd " display command on bottom
" set cursorline " make cursorline for current line
" set clipboard=unnamedplus


" <---  PLUGIN  --->
" [ minpac ]
packadd minpac
command! PackUpdate call minpac#update()
command! PackClean call minpac#clean()
call minpac#init()
call minpac#add('https://github.com/tomtom/tcomment_vim.git')
" call minpac#add('https://github.com/neoclide/coc.nvim.git')


" <--- Project Specific .vimrc --->
" reference: https://andrew.stwrt.ca/posts/project-specific-vimrc/
set exrc
set secure

