" <----------   CUSTOMIZATION   ---------->

syntax on
set number
set colorcolumn=80
set autoread

" set encoding utf 8
set encoding=utf-8
set fileencoding=utf-8

" set tab
set tabstop=4
set softtabstop=4
set shiftwidth=4
set expandtab
set smarttab

color ron
set listchars=tab:▸\


" <----------   VUNDLE & PLUGIN   ---------->
set nocompatible              " be iMproved, required
filetype off                  " required

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
" alternatively, pass a path where Vundle should install plugins
"call vundle#begin('~/some/path/here')

" let Vundle manage Vundle, required
Plugin 'VundleVim/Vundle.vim'

" < Custom Plugin >
" autocomplete
" Plugin 'ervandew/supertab'
Plugin 'valloric/youcompleteme'

" check syntax
Plugin 'scrooloose/syntastic'

" comment tool
Plugin 'tomtom/tcomment_vim'

" display indent
Plugin 'nathanaelkane/vim-indent-guides'


call vundle#end()            " required
filetype plugin indent on    " required
" To ignore plugin indent changes, instead use:
"filetype plugin on
"
" Brief help
" :PluginList       - lists configured plugins
" :PluginInstall    - installs plugins; append `!` to update or just :PluginUpdate
" :PluginSearch foo - searches for foo; append `!` to refresh local cache
" :PluginClean      - confirms removal of unused plugins; append `!` to auto-approve removal
"
" see :h vundle for more details or wiki for FAQ
" Put your non-Plugin stuff after this line

